apiVersion: platform.kamiwaza.io/v1alpha1
kind: KamiwazaPlatform
metadata:
  name: kamiwaza
  namespace: kw-cert-platform
  annotations:
    transport.kamiwaza.io/rotate-authority: null
    transport.kamiwaza.io/rotate-operation: null
