apiVersion: platform.kamiwaza.io/v1alpha1
kind: KamiwazaNodePool
metadata:
  name: application-workers
  namespace: kw-multi-zone
  labels:
    platform.kamiwaza.io/cluster: kamiwaza
spec:
  capability: applicationAPI
  replicas: 3
  placement:
    topologySpreadConstraints:
      - maxSkew: 1
        minDomains: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
  disruption:
    maxUnavailable: 1
