apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kamiwaza

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: auth-gateway-edge
    files:
      - secret=local-secrets/auth-gateway-edge.secret

  - name: traefik-client-ca
    files:
      - ca.crt=local-secrets/traefik-client-ca.crt
