apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: kuberay
---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: kamiwaza-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kamiwaza
