apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      group: serving.kamiwaza.io
      version: v1alpha1
      kind: ModelDeployment
      name: smollm2
    patch: |-
      - op: add
        path: /spec/accelerator
        value:
          resourceName: nvidia.com/gpu
          count: 1
