apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - etcd-servicemonitor.yaml
  - compute-podmonitor.yaml
  - metadata-catalog-servicemonitor.yaml
  - authorization-podmonitor.yaml
  - cert-manager-servicemonitor.yaml
  - scrape-networkpolicies.yaml
